### ISSUE TITLE
Error installing nos-client on windows

### ISSUE THREAD

**Issue by SharedMocha** [nos/client#180]
Unable to install nos-client on windows.

## Expected Behavior
Installation of nos-client should be smooth on windows

## Current Behavior
Getting below error. I have windows sdk,python installed.
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory [C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid\build\hidapi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid

## Possible Solution
Reinstalling windows sdk. I tried this but no luck yet.

## Steps to Reproduce (for bugs)
Use windows machine and clone nos-client and run the first command "yarn install && yarn start"

## Context
I wanted to develop a dapp which i am not able to do as i am struck here

## Your Environment
Windows 10
Python 2.7.14
node 10.2.1
yarn 1.6.0
npm 6.1.0

**Comment by SharedMocha** [comment]
This might not be a problem with nos-client directly but issue with windows sdk

**Comment by SharedMocha** [comment]
Full Log-
>yarn install
yarn install v1.6.0
[1/4] Resolving packages...
warning bignumber.js@7.0.1: Custom ALPHABET bug fixed in v7.0.2
warning redux-mock-store@1.5.1: breaking changes in minor version
[2/4] Fetching packages...
info app-builder-bin-linux@1.8.6: The platform "win32" is incompatible with this module.
info "app-builder-bin-linux@1.8.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.8.6: The platform "win32" is incompatible with this module.
info "app-builder-bin-mac@1.8.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-import-resolver-babel-module@4.0.0" has unmet peer dependency "babel-core@^6.0.0".
[4/4] Building fresh packages...
[1/4] ⡀ node-hid: C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': N
[2/4] ⢀ electron
[-/4] ⢀ waiting...
[4/4] ⢀ node-sass: Creating "Release\obj\libsass\libsass.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
error C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid
Output:
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\node-hid-v0.7.2-node-v64-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\htammare\AppData\Roaming\npm-cache\_prebuilds\https-github.com-node-hid-node-hid-releases-download-v0.7.2-node-hid-v0.7.2-node-v64-win32-x64.tar.gz
prebuild-install http request GET https://github.com/node-hid/node-hid/releases/download/v0.7.2/node-hid-v0.7.2-node-v64-win32-x64.tar.gz
prebuild-install http 404 https://github.com/node-hid/node-hid/releases/download/v0.7.2/node-hid-v0.7.2-node-v64-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=10.2.1 runtime=node arch=x64 platform=win32)

C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | win32 | x64
gyp info spawn C:\Users\htammare\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\htammare\\Documents\\GitHub\\client\\node_modules\\node-hid\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\htammare\\.node-gyp\\10.2.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\htammare\\.node-gyp\\10.2.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\htammare\\.node-gyp\\10.2.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\htammare\\Documents\\GitHub\\client\\node_modules\\node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\htammare\\Documents\\GitHub\\client\\node_modules\\node-hid\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  hid.c
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory [C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid\build\hidapi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\htammare\Documents\GitHub\client\node_modules\node-hid

**Comment by mhuggins** [comment]
This looks related, can you try this?

https://stackoverflow.com/a/42258579/107277

> Repair / Reinstall visual studio. Make sure that the Windows SDK option (Probably 8.1 in your case) is ticked, As you can see in this picture:
> 
> ![reinstall](https://i.stack.imgur.com/rAknB.png)

**Comment by SharedMocha** [comment]
I tried it but it didn't work.
I will try to uninstall and reinstall everything.

**Comment by DalderupMaurice** [comment]
I've seen this issue a dozen times before with people having Visual Studio installed on their Windows PC. 

1. You should execute this `npm install --global --production windows-build-tools`
2. Install this http://landinghub.visualstudio.com/visual-cpp-build-tools
3. and generate an empty C++ project in visual studio - doing this installs some libraries which fixes the error lol 😄
